<?php
/**
 * Implements hook_requirements().
 *
 * @ingroup tripal_domain
 */
function tripal_domain_requirements($phase) {
  $requirements = array();
  if ($phase == 'install') {
    // make sure chado is installed
    if (!$GLOBALS["chado_is_installed"]) {
      $requirements ['tripal_domain'] = array(
          'title' => "tripal_domain",
          'value' => "ERROR: Chado must be installed before this module can be enabled",
          'severity' => REQUIREMENT_ERROR,
      );
    }
  }
  return $requirements;
}





/* hook_enable()*/

function tripal_domain_enable(){
$permissions = array('access chado_domain content');
tripal_domain_grant_permissions(DRUPAL_AUTHENTICATED_RID, $permissions);
$permissions_anonym = array('access chado_domain content');
tripal_domain_grant_permissions(DRUPAL_ANONYMOUS_RID, $permissions_anonym);
$permissions_admin = array('administer tripal domain');
tripal_domain_grant_permissions(DRUPAL_AUTHENTICATED_RID, $permissions_admin);
}
 


/**
 * Implements hook_install()
 * Allows installation of the tripal_domain module
 */


function tripal_domain_install() {
   // add the materializedviews
   tripal_domain_add_mview();

   // we want to integrate the materialized views so that they
   // are available for Drupal Views, upon which our search forms are built
   tripal_domain_intergrate_view();
  
   $mview_id =  tripal_get_mview_id('domain');   
  
   tripal_populate_mview($mview_id);

}

/**
 * Implementation of hook_grant_permissions(). peu added
 */


function tripal_domain_grant_permissions($rid, array $permissions = array()) {
   
   // this line doesn't work on install / enable hooks
     $modules = user_permission_get_modules();
    // Grant new permissions for the role.
    foreach ($permissions as $name) {
        db_merge('role_permission')
        ->key(array(
            'rid' => $rid,
            'permission' => $name,
        ))
        ->fields(array(
      //hard-coded module name here as $modules was not working -peu   
           'module' => 'tripal_domain',
       ))
        ->execute();
    }
    

    // Clear the user access cache.
    drupal_static_reset('user_access');
    drupal_static_reset('user_role_permissions');
}


/**
 * Implementation of hook_uninstall().
 */
function tripal_domain_uninstall() {

 //not needed?peu $drop_tbl   = chado_query("DROP TABLE IF EXISTS domain");  
  // Drop the MView table if it exists
  $mview_id =  tripal_get_mview_id('domain');
  if ($mview_id) {
    tripal_delete_mview($mview_id);
  }
  //Remove views integration
  // Note: tripal_remove_views_intergration accepts table_name and priority in a key value form. 

  $delete_view=array(
    'table_name' => 'domain',
    'priority' => '-1',
  );
  tripal_remove_views_integration($delete_view); 

}



function tripal_domain_add_mview(){
 
 
  //Materialized view addition
  
 $sql_query="WITH count_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id from feature f INNER JOIN featureloc floc on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and f.name is not null and O.genus!='consensus' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') group by floc.srcfeature_id),
count_glyma_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Glycine' and O.species='max'  and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_medtr_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Medicago' and O.species='truncatula' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_lotja_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Lotus' and O.species='japonicus' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_phavu_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Phaseolus' and O.species='vulgaris' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_aradu_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Arachis' and O.species='duranensis' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_araip_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Arachis' and O.species='ipaensis' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_arahy_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Arachis' and O.species='hypogaea' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_lupan_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Lupinus' and O.species='angustifolius' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_lupal_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Lupinus' and O.species='albus' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_pissa_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Pisum' and O.species='sativum' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_cajca_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Cajanus' and O.species='cajan' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_cicar_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Cicer' and O.species='arietinum_CDCFrontier' and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_vigun_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Vigna' and O.species='unguiculata'  and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_vigra_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Vigna' and O.species='radiata'  and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_tripr_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Trifolium' and O.species='pratense'  and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
count_vigan_match as (select count(distinct floc2.srcfeature_id) count, floc.srcfeature_id FROM featureloc floc INNER JOIN feature f on floc.feature_id=f.feature_id INNER JOIN featureloc floc2 ON floc2.feature_id=floc.feature_id INNER JOIN organism O on O.organism_id=f.organism_id where floc2.rank=0 and O.genus='Vigna' and O.species='angularis'  and f.type_id=(select cvterm_id from cvterm c,cv where c.name='protein_hmm_match' and c.cv_id=cv.cv_id and cv.name='sequence') GROUP BY floc.srcfeature_id),
description as (select c.name,c.definition,cd.dbxref_id, d.accession, f.feature_id from dbxref d INNER JOIN cvterm c on d.dbxref_id=c.dbxref_id INNER JOIN cvterm_dbxref cd on c.cvterm_id = cd.cvterm_id INNER JOIN feature f on f.name = (select accession from dbxref where dbxref_id = cd.dbxref_id and db_id IN (select db_id from db where name IN ('PFAM','SMART','PIRSF','TIGRFAMs','GENE3D')))),
trees_per_domain as (SELECT count(DISTINCT t.name) count, f1.name FROM phylotree t JOIN analysis a ON t.analysis_id=a.analysis_id JOIN phylonode n ON t.phylotree_id=n.phylotree_id JOIN feature f2 ON n.feature_id = f2.feature_id JOIN featureloc ON featureloc.srcfeature_id=f2.feature_id JOIN cvterm cvt2 ON cvt2.cvterm_id=f2.type_id JOIN feature f1 ON featureloc.feature_id=f1.feature_id WHERE cvt2.name='polypeptide' AND a.name='Phytozome 10.2 Angiosperm Gene Family Derived Trees' GROUP BY f1.name),
consensus_tree_features_per_domain as (SELECT count(DISTINCT f.name) count, f2.name domain_name from feature f JOIN phylotree p ON f.name=p.name || '-consensus' JOIN featureloc ON featureloc.srcfeature_id=f.feature_id JOIN cvterm cvt ON cvt.cvterm_id=f.type_id JOIN feature f2 ON featureloc.feature_id=f2.feature_id WHERE cvt.name='consensus_region' GROUP BY domain_name)
SELECT
feature.feature_id AS feature_feature_id,
feature.name AS feature_name,
description.name AS cvterm_name,
description.accession AS IPRterm,
description.definition AS feature_desc,
coalesce(count_match.count, 0) as total_count,
coalesce(count_glyma_match.count, 0) as glyma_count,
coalesce(count_medtr_match.count, 0) as medtr_count,
coalesce(count_lotja_match.count, 0) as lotja_count,
coalesce(count_phavu_match.count, 0) as phavu_count,
coalesce(count_aradu_match.count, 0) as aradu_count,
coalesce(count_araip_match.count, 0) as araip_count,
coalesce(count_arahy_match.count, 0) as arahy_count,
coalesce(count_lupan_match.count, 0) as lupan_count,
coalesce(count_lupal_match.count, 0) as lupal_count,
coalesce(count_pissa_match.count, 0) as pissa_count,
coalesce(count_cajca_match.count, 0) as cajca_count,
coalesce(count_cicar_match.count, 0) as cicar_count,
coalesce(count_vigun_match.count, 0) as vigun_count,
coalesce(count_vigra_match.count, 0) as vigra_count,
coalesce(count_tripr_match.count, 0) as tripr_count,
coalesce(count_vigan_match.count, 0) as vigan_count,
coalesce(trees_per_domain.count, 0) as tree_count,
coalesce(consensus_tree_features_per_domain.count, 0) as consensus_tree_count
from chado.feature feature 
LEFT JOIN chado_feature chado_feature ON feature.feature_id = chado_feature.feature_id
LEFT JOIN count_match count_match ON feature.feature_id = count_match.srcfeature_id
LEFT JOIN count_glyma_match ON feature.feature_id = count_glyma_match.srcfeature_id
LEFT JOIN count_medtr_match ON feature.feature_id = count_medtr_match.srcfeature_id
LEFT JOIN count_lotja_match ON feature.feature_id = count_lotja_match.srcfeature_id
LEFT JOIN count_phavu_match ON feature.feature_id = count_phavu_match.srcfeature_id
LEFT JOIN count_aradu_match ON feature.feature_id = count_aradu_match.srcfeature_id
LEFT JOIN count_araip_match ON feature.feature_id = count_araip_match.srcfeature_id
LEFT JOIN count_arahy_match ON feature.feature_id = count_arahy_match.srcfeature_id
LEFT JOIN count_lupan_match ON feature.feature_id = count_lupan_match.srcfeature_id
LEFT JOIN count_lupal_match ON feature.feature_id = count_lupal_match.srcfeature_id
LEFT JOIN count_pissa_match ON feature.feature_id = count_pissa_match.srcfeature_id
LEFT JOIN count_cajca_match ON feature.feature_id = count_cajca_match.srcfeature_id
LEFT JOIN count_cicar_match ON feature.feature_id = count_cicar_match.srcfeature_id
LEFT JOIN count_vigun_match ON feature.feature_id = count_vigun_match.srcfeature_id
LEFT JOIN count_vigra_match ON feature.feature_id = count_vigra_match.srcfeature_id
LEFT JOIN count_tripr_match ON feature.feature_id = count_tripr_match.srcfeature_id
LEFT JOIN count_vigan_match ON feature.feature_id = count_vigan_match.srcfeature_id
LEFT JOIN description ON feature.feature_id = description.feature_id
LEFT JOIN trees_per_domain ON feature.name = trees_per_domain.name
LEFT JOIN consensus_tree_features_per_domain ON feature.name = consensus_tree_features_per_domain.domain_name
where feature.type_id IN (select cvterm_id from cvterm c,cv where c.name='polypeptide_domain' and c.cv_id=cv.cv_id and cv.name='sequence')";



    //Table domain description

	$schema = array (
  'table' => 'domain',
  'fields' => array (
    'feature_feature_id' => array (
      'type' => 'int',
      'not null' => false,
    ),
    'feature_name' => array (
      'type' => 'text',
      'not null' => false,
    ),
   'cvterm_name' => array (
      'type' => 'text',
      'not null' => false,
    ),
   'IPRterm' => array (
     'type' => 'text',
      'not null' => false,
    ),
   'feature_desc' => array (
    'type' => 'text',
      'not null' => false,
    ),
    'total_count' => array (
      'type' => 'int',
      'not null' => false,
      ),
    'glyma_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
    'medtr_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
    'lotja_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
    'phavu_count' => array (
      'type' => 'int',
      'not null' => false,
     
    ),
    'aradu_count' => array (
      'type' => 'int',
      'not null' => false,
     
    ),
    'araip_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
    'arahy_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
    'lupan_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
    'lupal_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
    'pissa_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
    'cajca_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
    'cicar_count' => array (
      'type' => 'int',
      'not null' => false,
      
    ),
   'vigun_count' => array (
      'type' => 'int',
      'not null' => false,

    ),  
   'vigra_count' => array (
      'type' => 'int',
      'not null' => false,

    ),  
   'tripr_count' => array (
      'type' => 'int',
      'not null' => false,

    ),  
 
    'vigan_count' => array (
      'type' => 'int',
      'not null' => false,

    ),

    'tree_count' => array (
    'type' => 'int',
   'not null' => false,
  ),

  'consensus_tree_count' => array (
  'type' => 'int',
   'not null' => false,
   )

),
  'primary key' => array (
    0 => 'feature_feature_id',
  ),
);



   // add a comment to make sure this view makes sense to the site administator
  $comment = t('This view is used to provide a table for searching Protein Domain Pages.');
  print "\nCreating domain mview.....\n";
  tripal_add_mview(
    'domain', // name of materialized view
    'tripal_domain', // name of module submitting view
    $schema,      // schema api array representation
    $sql_query,         // sql query that loads the mview
    $comment );


}

/**
 * Integrate the qtl_search materialized view for use by Drupal Views and
 * our search form
 */

function tripal_domain_intergrate_view(){
    $integration = array (
  'table' => 'domain',
  'name' => 'domain',
  'type' => 'chado',
  'description' => 'view integration for Materialzied view "domain" ',
  'priority' => '-1',
  'base_table' => '1',
  'fields' => array (
    'feature_feature_id' => array (
      'name' => 'feature_feature_id',
      'title' => 'Feature Feature Id',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'feature_name' => array (
      'name' => 'feature_name',
      'title' => 'Domain ID',
      'description' => 'TODO: please describe this field!',
      'type' => 'text',
      'handlers' => array (
        'filter' => array (
          'name' => 'tripal_views_handler_filter_select_string',
        ),
        'field' => array (
          'name' => 'views_handler_field',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_string',
        ),
      ),
      'joins' => array (
      ),
    ),
    'cvterm_name' => array (
      'name' => 'cvterm_name',
      'title' => 'Domain Name',
      'description' => 'A short name of domain accession ',
      'type' => 'text',
      'handlers' => array (
        'filter' => array (
          'name' => 'tripal_views_handler_filter_select_string',
        ),
        'field' => array (
          'name' => 'views_handler_field',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_string',
        ),
      ),
      'joins' => array (
      ),
    ),
    'IPRterm' => array (
      'name' => 'IPRterm',
      'title' => 'Interpro term',
      'description' => 'Interpro IPR term',
      'type' => 'text',
      'handlers' => array (
        'filter' => array (
          'name' => 'tripal_views_handler_filter_select_string',
        ),
        'field' => array (
          'name' => 'views_handler_field',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_string',
        ),
      ),
      'joins' => array (
      ),
    ),
    'feature_desc' => array (
      'name' => 'feature_desc',
      'title' => 'Description',
      'description' => 'TODO: please describe this field!',
      'type' => 'text',
      'handlers' => array (
        'filter' => array (
          'name' => 'tripal_views_handler_filter_select_string',
        ),
        'field' => array (
          'name' => 'views_handler_field',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_string',
        ),
      ),
      'joins' => array (
      ),
    ),
    'total_count' => array (
      'name' => 'total_count',
      'title' => 'Gene Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'glyma_count' => array (
      'name' => 'glyma_count',
      'title' => 'Glyma Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'medtr_count' => array (
      'name' => 'medtr_count',
      'title' => 'Medtr Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'lotja_count' => array (
      'name' => 'lotja_count',
      'title' => 'Lotja Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'phavu_count' => array (
      'name' => 'phavu_count',
      'title' => 'Phavu Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'aradu_count' => array (
      'name' => 'aradu_count',
      'title' => 'Aradu Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'araip_count' => array (
      'name' => 'araip_count',
      'title' => 'Araip Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'arahy_count' => array (
      'name' => 'arahy_count',
      'title' => 'Arahy Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'lupan_count' => array (
      'name' => 'lupan_count',
      'title' => 'Lupan Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'lupal_count' => array (
      'name' => 'lupal_count',
      'title' => 'Lupal Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'pissa_count' => array (
      'name' => 'pissa_count',
      'title' => 'Pissa Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'cajca_count' => array (
      'name' => 'cajca_count',
      'title' => 'Cajca Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),
    'cicar_count' => array (
      'name' => 'cicar_count',
      'title' => 'Cicar (CDCFrontier) Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),

'vigun_count' => array (
      'name' => 'vigun_count',
      'title' => 'Vigun Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),

'vigra_count' => array (
      'name' => 'vigra_count',
      'title' => 'Vigra Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),

'tripr_count' => array (
      'name' => 'tripr_count',
      'title' => 'Tripr Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),

'vigan_count' => array (
      'name' => 'vigan_count',
      'title' => 'Vigan Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),

 
'tree_count' => array (
     'name' => 'tree_count',
    'title' => 'Phylotree Count',
     'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),


'consensus_tree_count' => array (
      'name' => 'consensus_tree_count',
      'title' => 'Family Count',
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'handlers' => array (
        'filter' => array (
          'name' => 'views_handler_filter_numeric',
        ),
        'field' => array (
          'name' => 'views_handler_field_numeric',
        ),
        'sort' => array (
          'name' => 'views_handler_sort',
        ),
        'argument' => array (
          'name' => 'views_handler_argument_numeric',
        ),
      ),
      'joins' => array (
      ),
    ),

  ),
);

// add the array above that will integrate our qtl_search materialized view
  // for use with Drupal Views
  tripal_add_views_integration($integration);

}





